//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Avtomatizaciya_prodazhi3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Долж.
    /// </summary>
    // *** Start programmer edit section *** (Долж CustomAttributes)

    // *** End programmer edit section *** (Долж CustomAttributes)
    [AutoAltered()]
    [Caption("Должность")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДолжE", new string[] {
            "Должность as \'Должность\'"})]
    [View("ДолжL", new string[] {
            "Должность as \'Должность\'"})]
    public class Долж : ICSSoft.STORMNET.DataObject
    {
        
        private string fДолжность;
        
        // *** Start programmer edit section *** (Долж CustomMembers)

        // *** End programmer edit section *** (Долж CustomMembers)

        
        /// <summary>
        /// Должность.
        /// </summary>
        // *** Start programmer edit section *** (Долж.Должность CustomAttributes)

        // *** End programmer edit section *** (Долж.Должность CustomAttributes)
        [StrLen(255)]
        public virtual string Должность
        {
            get
            {
                // *** Start programmer edit section *** (Долж.Должность Get start)

                // *** End programmer edit section *** (Долж.Должность Get start)
                string result = this.fДолжность;
                // *** Start programmer edit section *** (Долж.Должность Get end)

                // *** End programmer edit section *** (Долж.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Долж.Должность Set start)

                // *** End programmer edit section *** (Долж.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (Долж.Должность Set end)

                // *** End programmer edit section *** (Долж.Должность Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДолжE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжE", typeof(IIS.Avtomatizaciya_prodazhi3.Долж));
                }
            }
            
            /// <summary>
            /// "ДолжL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжL", typeof(IIS.Avtomatizaciya_prodazhi3.Долж));
                }
            }
        }
    }
}
