//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Avtomatizaciya_prodazhi3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ед измер.
    /// </summary>
    // *** Start programmer edit section *** (ЕдИзмер CustomAttributes)

    // *** End programmer edit section *** (ЕдИзмер CustomAttributes)
    [AutoAltered()]
    [Caption("Единицы измерения")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЕдИзмерE", new string[] {
            "ЕдИзм as \'Единицы измерения\'"})]
    [View("ЕдИзмерL", new string[] {
            "ЕдИзм as \'Ед изм\'"})]
    public class ЕдИзмер : ICSSoft.STORMNET.DataObject
    {
        
        private string fЕдИзм;
        
        // *** Start programmer edit section *** (ЕдИзмер CustomMembers)

        // *** End programmer edit section *** (ЕдИзмер CustomMembers)

        
        /// <summary>
        /// ЕдИзм.
        /// </summary>
        // *** Start programmer edit section *** (ЕдИзмер.ЕдИзм CustomAttributes)

        // *** End programmer edit section *** (ЕдИзмер.ЕдИзм CustomAttributes)
        [StrLen(255)]
        public virtual string ЕдИзм
        {
            get
            {
                // *** Start programmer edit section *** (ЕдИзмер.ЕдИзм Get start)

                // *** End programmer edit section *** (ЕдИзмер.ЕдИзм Get start)
                string result = this.fЕдИзм;
                // *** Start programmer edit section *** (ЕдИзмер.ЕдИзм Get end)

                // *** End programmer edit section *** (ЕдИзмер.ЕдИзм Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЕдИзмер.ЕдИзм Set start)

                // *** End programmer edit section *** (ЕдИзмер.ЕдИзм Set start)
                this.fЕдИзм = value;
                // *** Start programmer edit section *** (ЕдИзмер.ЕдИзм Set end)

                // *** End programmer edit section *** (ЕдИзмер.ЕдИзм Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЕдИзмерE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЕдИзмерE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЕдИзмерE", typeof(IIS.Avtomatizaciya_prodazhi3.ЕдИзмер));
                }
            }
            
            /// <summary>
            /// "ЕдИзмерL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЕдИзмерL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЕдИзмерL", typeof(IIS.Avtomatizaciya_prodazhi3.ЕдИзмер));
                }
            }
        }
    }
}
