//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Avtomatizaciya_prodazhi3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Зак покуп.
    /// </summary>
    // *** Start programmer edit section *** (ЗакПокуп CustomAttributes)

    // *** End programmer edit section *** (ЗакПокуп CustomAttributes)
    [AutoAltered()]
    [Caption("Заказ покупателя")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗакПокупE", new string[] {
            "Менедж as \'Менеджер\'",
            "ДатаНачала as \'Дата начала\'",
            "ДатаОкончания as \'Дата окончания\'",
            "Организ as \'Организация\'",
            "Организ.Организация as \'Организация\'",
            "Подраз as \'Подразделение\'",
            "Подраз.Подразделение as \'Подразделение\'",
            "Склады as \'Склад\'",
            "Склады.Склад as \'Склад\'",
            "Контр as \'Контрагент\'",
            "Контр.Контрагент as \'Контрагент\'",
            "СостОплат as \'Состояние оплаты\'",
            "СостОтгруз as \'Состояние отгрузки\'",
            "Сумма as \'Сумма\'",
            "СумВклНДС as \'Сумма включая НДС\'"}, Hidden=new string[] {
            "Организ.Организация",
            "Подраз.Подразделение",
            "Склады.Склад",
            "Контр.Контрагент"})]
    [AssociatedDetailViewAttribute("ЗакПокупE", "ТЧТовИУс", "ТЧТовИУсE", true, "", "Табличная часть товаров и услуг", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЗакПокупE", "Менедж", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "")]
    [MasterViewDefineAttribute("ЗакПокупE", "Организ", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Организация")]
    [MasterViewDefineAttribute("ЗакПокупE", "Подраз", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Подразделение")]
    [MasterViewDefineAttribute("ЗакПокупE", "Склады", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Склад")]
    [MasterViewDefineAttribute("ЗакПокупE", "Контр", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Контрагент")]
    [View("ЗакПокупL", new string[] {
            "ДатаОкончания as \'Дата окончания\'",
            "ДатаНачала as \'Дата начала\'",
            "СумВклНДС as \'Сум вкл НДС\'",
            "СостОтгруз as \'Сост отгруз\'",
            "СостОплат as \'Сост оплат\'",
            "Сумма as \'Сумма\'",
            "Склады.Склад as \'Склад\'",
            "Организ.Организация as \'Организация\'",
            "Контр.Контрагент as \'Контрагент\'",
            "Подраз.Подразделение as \'Подразделение\'"})]
    public class ЗакПокуп : IIS.Avtomatizaciya_prodazhi3.ОтчОПрод
    {
        
        // *** Start programmer edit section *** (ЗакПокуп CustomMembers)

        // *** End programmer edit section *** (ЗакПокуп CustomMembers)

        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗакПокупE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗакПокупE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗакПокупE", typeof(IIS.Avtomatizaciya_prodazhi3.ЗакПокуп));
                }
            }
            
            /// <summary>
            /// "ЗакПокупL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗакПокупL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗакПокупL", typeof(IIS.Avtomatizaciya_prodazhi3.ЗакПокуп));
                }
            }
        }
    }
}
