//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Avtomatizaciya_prodazhi3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Кол в рез.
    /// </summary>
    // *** Start programmer edit section *** (КолВРез CustomAttributes)

    // *** End programmer edit section *** (КолВРез CustomAttributes)
    [AutoAltered()]
    [Caption("Количество в резерве")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КолВРезE", new string[] {
            "Номенк as \'Номенклатура\'",
            "Номенк.Номен as \'Номенклатура\'",
            "Количество as \'Количество\'"}, Hidden=new string[] {
            "Номенк.Номен"})]
    [MasterViewDefineAttribute("КолВРезE", "Номенк", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номен")]
    [View("КолВРезL", new string[] {
            "Количество as \'Количество\'",
            "Номенк.Номен as \'Номен\'"})]
    public class КолВРез : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private IIS.Avtomatizaciya_prodazhi3.Номенк fНоменк;
        
        // *** Start programmer edit section *** (КолВРез CustomMembers)

        // *** End programmer edit section *** (КолВРез CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (КолВРез.Количество CustomAttributes)

        // *** End programmer edit section *** (КолВРез.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (КолВРез.Количество Get start)

                // *** End programmer edit section *** (КолВРез.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (КолВРез.Количество Get end)

                // *** End programmer edit section *** (КолВРез.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КолВРез.Количество Set start)

                // *** End programmer edit section *** (КолВРез.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (КолВРез.Количество Set end)

                // *** End programmer edit section *** (КолВРез.Количество Set end)
            }
        }
        
        /// <summary>
        /// Кол в рез.
        /// </summary>
        // *** Start programmer edit section *** (КолВРез.Номенк CustomAttributes)

        // *** End programmer edit section *** (КолВРез.Номенк CustomAttributes)
        [PropertyStorage(new string[] {
                "Номенк"})]
        [NotNull()]
        public virtual IIS.Avtomatizaciya_prodazhi3.Номенк Номенк
        {
            get
            {
                // *** Start programmer edit section *** (КолВРез.Номенк Get start)

                // *** End programmer edit section *** (КолВРез.Номенк Get start)
                IIS.Avtomatizaciya_prodazhi3.Номенк result = this.fНоменк;
                // *** Start programmer edit section *** (КолВРез.Номенк Get end)

                // *** End programmer edit section *** (КолВРез.Номенк Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КолВРез.Номенк Set start)

                // *** End programmer edit section *** (КолВРез.Номенк Set start)
                this.fНоменк = value;
                // *** Start programmer edit section *** (КолВРез.Номенк Set end)

                // *** End programmer edit section *** (КолВРез.Номенк Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КолВРезE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КолВРезE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КолВРезE", typeof(IIS.Avtomatizaciya_prodazhi3.КолВРез));
                }
            }
            
            /// <summary>
            /// "КолВРезL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КолВРезL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КолВРезL", typeof(IIS.Avtomatizaciya_prodazhi3.КолВРез));
                }
            }
        }
    }
}
