//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Avtomatizaciya_prodazhi3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Номенк.
    /// </summary>
    // *** Start programmer edit section *** (Номенк CustomAttributes)

    // *** End programmer edit section *** (Номенк CustomAttributes)
    [AutoAltered()]
    [Caption("Номеклатура")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НоменкE", new string[] {
            "Номен as \'Номенклатура\'",
            "ЕдИзмер as \'Единицы измерения\'",
            "ЕдИзмер.ЕдИзм as \'Единицы измерения\'"}, Hidden=new string[] {
            "ЕдИзмер.ЕдИзм"})]
    [MasterViewDefineAttribute("НоменкE", "ЕдИзмер", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ЕдИзм")]
    [View("НоменкL", new string[] {
            "Номен as \'Номен\'",
            "ЕдИзмер.ЕдИзм as \'Ед изм\'"})]
    public class Номенк : ICSSoft.STORMNET.DataObject
    {
        
        private string fНомен;
        
        private IIS.Avtomatizaciya_prodazhi3.ЕдИзмер fЕдИзмер;
        
        // *** Start programmer edit section *** (Номенк CustomMembers)

        // *** End programmer edit section *** (Номенк CustomMembers)

        
        /// <summary>
        /// Номен.
        /// </summary>
        // *** Start programmer edit section *** (Номенк.Номен CustomAttributes)

        // *** End programmer edit section *** (Номенк.Номен CustomAttributes)
        [StrLen(255)]
        public virtual string Номен
        {
            get
            {
                // *** Start programmer edit section *** (Номенк.Номен Get start)

                // *** End programmer edit section *** (Номенк.Номен Get start)
                string result = this.fНомен;
                // *** Start programmer edit section *** (Номенк.Номен Get end)

                // *** End programmer edit section *** (Номенк.Номен Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенк.Номен Set start)

                // *** End programmer edit section *** (Номенк.Номен Set start)
                this.fНомен = value;
                // *** Start programmer edit section *** (Номенк.Номен Set end)

                // *** End programmer edit section *** (Номенк.Номен Set end)
            }
        }
        
        /// <summary>
        /// Номенк.
        /// </summary>
        // *** Start programmer edit section *** (Номенк.ЕдИзмер CustomAttributes)

        // *** End programmer edit section *** (Номенк.ЕдИзмер CustomAttributes)
        [PropertyStorage(new string[] {
                "ЕдИзмер"})]
        [NotNull()]
        public virtual IIS.Avtomatizaciya_prodazhi3.ЕдИзмер ЕдИзмер
        {
            get
            {
                // *** Start programmer edit section *** (Номенк.ЕдИзмер Get start)

                // *** End programmer edit section *** (Номенк.ЕдИзмер Get start)
                IIS.Avtomatizaciya_prodazhi3.ЕдИзмер result = this.fЕдИзмер;
                // *** Start programmer edit section *** (Номенк.ЕдИзмер Get end)

                // *** End programmer edit section *** (Номенк.ЕдИзмер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенк.ЕдИзмер Set start)

                // *** End programmer edit section *** (Номенк.ЕдИзмер Set start)
                this.fЕдИзмер = value;
                // *** Start programmer edit section *** (Номенк.ЕдИзмер Set end)

                // *** End programmer edit section *** (Номенк.ЕдИзмер Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "НоменкE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НоменкE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НоменкE", typeof(IIS.Avtomatizaciya_prodazhi3.Номенк));
                }
            }
            
            /// <summary>
            /// "НоменкL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НоменкL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НоменкL", typeof(IIS.Avtomatizaciya_prodazhi3.Номенк));
                }
            }
        }
    }
}
