//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Avtomatizaciya_prodazhi3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Организ.
    /// </summary>
    // *** Start programmer edit section *** (Организ CustomAttributes)

    // *** End programmer edit section *** (Организ CustomAttributes)
    [AutoAltered()]
    [Caption("Организация")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОрганизE", new string[] {
            "Организация as \'Организация\'"})]
    [View("ОрганизL", new string[] {
            "Организация as \'Организация\'"})]
    public class Организ : ICSSoft.STORMNET.DataObject
    {
        
        private string fОрганизация;
        
        // *** Start programmer edit section *** (Организ CustomMembers)

        // *** End programmer edit section *** (Организ CustomMembers)

        
        /// <summary>
        /// Организация.
        /// </summary>
        // *** Start programmer edit section *** (Организ.Организация CustomAttributes)

        // *** End programmer edit section *** (Организ.Организация CustomAttributes)
        [StrLen(255)]
        public virtual string Организация
        {
            get
            {
                // *** Start programmer edit section *** (Организ.Организация Get start)

                // *** End programmer edit section *** (Организ.Организация Get start)
                string result = this.fОрганизация;
                // *** Start programmer edit section *** (Организ.Организация Get end)

                // *** End programmer edit section *** (Организ.Организация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организ.Организация Set start)

                // *** End programmer edit section *** (Организ.Организация Set start)
                this.fОрганизация = value;
                // *** Start programmer edit section *** (Организ.Организация Set end)

                // *** End programmer edit section *** (Организ.Организация Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОрганизE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОрганизE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОрганизE", typeof(IIS.Avtomatizaciya_prodazhi3.Организ));
                }
            }
            
            /// <summary>
            /// "ОрганизL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОрганизL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОрганизL", typeof(IIS.Avtomatizaciya_prodazhi3.Организ));
                }
            }
        }
    }
}
