//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Avtomatizaciya_prodazhi3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отч о прод.
    /// </summary>
    // *** Start programmer edit section *** (ОтчОПрод CustomAttributes)

    // *** End programmer edit section *** (ОтчОПрод CustomAttributes)
    [AutoAltered()]
    [Caption("Отчет о продаже")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтчОПродE", new string[] {
            "Менедж as \'Менеджер\'",
            "ДатаНачала as \'Дата Начала\'",
            "ДатаОкончания as \'Дата Окончания\'",
            "Организ as \'Организация\'",
            "Организ.Организация as \'Организация\'",
            "Склады as \'Склад\'",
            "Склады.Склад as \'Склад\'",
            "Подраз as \'Подразделение\'",
            "Подраз.Подразделение as \'Подразделение\'",
            "Контр as \'Контрагент\'",
            "Контр.Контрагент as \'Контрагент\'",
            "СостОплат as \'Состояние Оплаты\'",
            "СостОтгруз as \'Состояние Отгрузки\'",
            "Сумма as \'Сумма\'",
            "СумВклНДС as \'Сумма включая НДС\'"}, Hidden=new string[] {
            "Организ.Организация",
            "Склады.Склад",
            "Подраз.Подразделение",
            "Контр.Контрагент"})]
    [AssociatedDetailViewAttribute("ОтчОПродE", "ТЧТовИУс", "ТЧТовИУсE", true, "", "Табличная часть товаров и услуг", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ОтчОПродE", "Менедж", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "")]
    [MasterViewDefineAttribute("ОтчОПродE", "Организ", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Организация")]
    [MasterViewDefineAttribute("ОтчОПродE", "Склады", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Склад")]
    [MasterViewDefineAttribute("ОтчОПродE", "Подраз", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Подразделение")]
    [MasterViewDefineAttribute("ОтчОПродE", "Контр", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Контрагент")]
    [View("ОтчОПродL", new string[] {
            "Склады.Склад as \'Склад\'",
            "Организ.Организация as \'Организация\'",
            "Контр.Контрагент as \'Контрагент\'",
            "Подраз.Подразделение as \'Подразделение\'",
            "ДатаНачала",
            "ДатаОкончания",
            "СостОплат",
            "СостОтгруз",
            "СумВклНДС",
            "Сумма"})]
    public class ОтчОПрод : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаОкончания;
        
        private System.DateTime fДатаНачала = System.DateTime.Now;
        
        private IIS.Avtomatizaciya_prodazhi3.СостОтгр fСостОтгруз;
        
        private IIS.Avtomatizaciya_prodazhi3.СостОпл fСостОплат;
        
        private int fСумма;
        
        private bool fСумВклНДС;
        
        private IIS.Avtomatizaciya_prodazhi3.Организ fОрганиз;
        
        private IIS.Avtomatizaciya_prodazhi3.Контр fКонтр;
        
        private IIS.Avtomatizaciya_prodazhi3.Подраз fПодраз;
        
        private IIS.Avtomatizaciya_prodazhi3.Склады fСклады;
        
        private IIS.Avtomatizaciya_prodazhi3.Менедж fМенедж;
        
        private IIS.Avtomatizaciya_prodazhi3.DetailArrayOfТЧТовИУс fТЧТовИУс;
        
        // *** Start programmer edit section *** (ОтчОПрод CustomMembers)

        // *** End programmer edit section *** (ОтчОПрод CustomMembers)

        
        /// <summary>
        /// ДатаНачала.
        /// </summary>
        // *** Start programmer edit section *** (ОтчОПрод.ДатаНачала CustomAttributes)

        // *** End programmer edit section *** (ОтчОПрод.ДатаНачала CustomAttributes)
        public virtual System.DateTime ДатаНачала
        {
            get
            {
                // *** Start programmer edit section *** (ОтчОПрод.ДатаНачала Get start)

                // *** End programmer edit section *** (ОтчОПрод.ДатаНачала Get start)
                System.DateTime result = this.fДатаНачала;
                // *** Start programmer edit section *** (ОтчОПрод.ДатаНачала Get end)

                // *** End programmer edit section *** (ОтчОПрод.ДатаНачала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчОПрод.ДатаНачала Set start)

                // *** End programmer edit section *** (ОтчОПрод.ДатаНачала Set start)
                this.fДатаНачала = value;
                // *** Start programmer edit section *** (ОтчОПрод.ДатаНачала Set end)

                // *** End programmer edit section *** (ОтчОПрод.ДатаНачала Set end)
            }
        }
        
        /// <summary>
        /// ДатаОкончания.
        /// </summary>
        // *** Start programmer edit section *** (ОтчОПрод.ДатаОкончания CustomAttributes)

        // *** End programmer edit section *** (ОтчОПрод.ДатаОкончания CustomAttributes)
        public virtual System.DateTime ДатаОкончания
        {
            get
            {
                // *** Start programmer edit section *** (ОтчОПрод.ДатаОкончания Get start)

                // *** End programmer edit section *** (ОтчОПрод.ДатаОкончания Get start)
                System.DateTime result = this.fДатаОкончания;
                // *** Start programmer edit section *** (ОтчОПрод.ДатаОкончания Get end)

                // *** End programmer edit section *** (ОтчОПрод.ДатаОкончания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчОПрод.ДатаОкончания Set start)

                // *** End programmer edit section *** (ОтчОПрод.ДатаОкончания Set start)
                this.fДатаОкончания = value;
                // *** Start programmer edit section *** (ОтчОПрод.ДатаОкончания Set end)

                // *** End programmer edit section *** (ОтчОПрод.ДатаОкончания Set end)
            }
        }
        
        /// <summary>
        /// СостОплат.
        /// </summary>
        // *** Start programmer edit section *** (ОтчОПрод.СостОплат CustomAttributes)

        // *** End programmer edit section *** (ОтчОПрод.СостОплат CustomAttributes)
        public virtual IIS.Avtomatizaciya_prodazhi3.СостОпл СостОплат
        {
            get
            {
                // *** Start programmer edit section *** (ОтчОПрод.СостОплат Get start)

                // *** End programmer edit section *** (ОтчОПрод.СостОплат Get start)
                IIS.Avtomatizaciya_prodazhi3.СостОпл result = this.fСостОплат;
                // *** Start programmer edit section *** (ОтчОПрод.СостОплат Get end)

                // *** End programmer edit section *** (ОтчОПрод.СостОплат Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчОПрод.СостОплат Set start)

                // *** End programmer edit section *** (ОтчОПрод.СостОплат Set start)
                this.fСостОплат = value;
                // *** Start programmer edit section *** (ОтчОПрод.СостОплат Set end)

                // *** End programmer edit section *** (ОтчОПрод.СостОплат Set end)
            }
        }
        
        /// <summary>
        /// СостОтгруз.
        /// </summary>
        // *** Start programmer edit section *** (ОтчОПрод.СостОтгруз CustomAttributes)

        // *** End programmer edit section *** (ОтчОПрод.СостОтгруз CustomAttributes)
        public virtual IIS.Avtomatizaciya_prodazhi3.СостОтгр СостОтгруз
        {
            get
            {
                // *** Start programmer edit section *** (ОтчОПрод.СостОтгруз Get start)

                // *** End programmer edit section *** (ОтчОПрод.СостОтгруз Get start)
                IIS.Avtomatizaciya_prodazhi3.СостОтгр result = this.fСостОтгруз;
                // *** Start programmer edit section *** (ОтчОПрод.СостОтгруз Get end)

                // *** End programmer edit section *** (ОтчОПрод.СостОтгруз Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчОПрод.СостОтгруз Set start)

                // *** End programmer edit section *** (ОтчОПрод.СостОтгруз Set start)
                this.fСостОтгруз = value;
                // *** Start programmer edit section *** (ОтчОПрод.СостОтгруз Set end)

                // *** End programmer edit section *** (ОтчОПрод.СостОтгруз Set end)
            }
        }
        
        /// <summary>
        /// СумВклНДС.
        /// </summary>
        // *** Start programmer edit section *** (ОтчОПрод.СумВклНДС CustomAttributes)

        // *** End programmer edit section *** (ОтчОПрод.СумВклНДС CustomAttributes)
        public virtual bool СумВклНДС
        {
            get
            {
                // *** Start programmer edit section *** (ОтчОПрод.СумВклНДС Get start)

                // *** End programmer edit section *** (ОтчОПрод.СумВклНДС Get start)
                bool result = this.fСумВклНДС;
                // *** Start programmer edit section *** (ОтчОПрод.СумВклНДС Get end)

                // *** End programmer edit section *** (ОтчОПрод.СумВклНДС Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчОПрод.СумВклНДС Set start)

                // *** End programmer edit section *** (ОтчОПрод.СумВклНДС Set start)
                this.fСумВклНДС = value;
                // *** Start programmer edit section *** (ОтчОПрод.СумВклНДС Set end)

                // *** End programmer edit section *** (ОтчОПрод.СумВклНДС Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (ОтчОПрод.Сумма CustomAttributes)

        // *** End programmer edit section *** (ОтчОПрод.Сумма CustomAttributes)
        public virtual int Сумма
        {
            get
            {
                // *** Start programmer edit section *** (ОтчОПрод.Сумма Get start)

                // *** End programmer edit section *** (ОтчОПрод.Сумма Get start)
                int result = this.fСумма;
                // *** Start programmer edit section *** (ОтчОПрод.Сумма Get end)

                // *** End programmer edit section *** (ОтчОПрод.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчОПрод.Сумма Set start)

                // *** End programmer edit section *** (ОтчОПрод.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (ОтчОПрод.Сумма Set end)

                // *** End programmer edit section *** (ОтчОПрод.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Отч о прод.
        /// </summary>
        // *** Start programmer edit section *** (ОтчОПрод.Контр CustomAttributes)

        // *** End programmer edit section *** (ОтчОПрод.Контр CustomAttributes)
        [PropertyStorage(new string[] {
                "Контр"})]
        [NotNull()]
        public virtual IIS.Avtomatizaciya_prodazhi3.Контр Контр
        {
            get
            {
                // *** Start programmer edit section *** (ОтчОПрод.Контр Get start)

                // *** End programmer edit section *** (ОтчОПрод.Контр Get start)
                IIS.Avtomatizaciya_prodazhi3.Контр result = this.fКонтр;
                // *** Start programmer edit section *** (ОтчОПрод.Контр Get end)

                // *** End programmer edit section *** (ОтчОПрод.Контр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчОПрод.Контр Set start)

                // *** End programmer edit section *** (ОтчОПрод.Контр Set start)
                this.fКонтр = value;
                // *** Start programmer edit section *** (ОтчОПрод.Контр Set end)

                // *** End programmer edit section *** (ОтчОПрод.Контр Set end)
            }
        }
        
        /// <summary>
        /// Отч о прод.
        /// </summary>
        // *** Start programmer edit section *** (ОтчОПрод.Менедж CustomAttributes)

        // *** End programmer edit section *** (ОтчОПрод.Менедж CustomAttributes)
        [PropertyStorage(new string[] {
                "Менедж"})]
        [NotNull()]
        public virtual IIS.Avtomatizaciya_prodazhi3.Менедж Менедж
        {
            get
            {
                // *** Start programmer edit section *** (ОтчОПрод.Менедж Get start)

                // *** End programmer edit section *** (ОтчОПрод.Менедж Get start)
                IIS.Avtomatizaciya_prodazhi3.Менедж result = this.fМенедж;
                // *** Start programmer edit section *** (ОтчОПрод.Менедж Get end)

                // *** End programmer edit section *** (ОтчОПрод.Менедж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчОПрод.Менедж Set start)

                // *** End programmer edit section *** (ОтчОПрод.Менедж Set start)
                this.fМенедж = value;
                // *** Start programmer edit section *** (ОтчОПрод.Менедж Set end)

                // *** End programmer edit section *** (ОтчОПрод.Менедж Set end)
            }
        }
        
        /// <summary>
        /// Отч о прод.
        /// </summary>
        // *** Start programmer edit section *** (ОтчОПрод.Организ CustomAttributes)

        // *** End programmer edit section *** (ОтчОПрод.Организ CustomAttributes)
        [PropertyStorage(new string[] {
                "Организ"})]
        [NotNull()]
        public virtual IIS.Avtomatizaciya_prodazhi3.Организ Организ
        {
            get
            {
                // *** Start programmer edit section *** (ОтчОПрод.Организ Get start)

                // *** End programmer edit section *** (ОтчОПрод.Организ Get start)
                IIS.Avtomatizaciya_prodazhi3.Организ result = this.fОрганиз;
                // *** Start programmer edit section *** (ОтчОПрод.Организ Get end)

                // *** End programmer edit section *** (ОтчОПрод.Организ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчОПрод.Организ Set start)

                // *** End programmer edit section *** (ОтчОПрод.Организ Set start)
                this.fОрганиз = value;
                // *** Start programmer edit section *** (ОтчОПрод.Организ Set end)

                // *** End programmer edit section *** (ОтчОПрод.Организ Set end)
            }
        }
        
        /// <summary>
        /// Отч о прод.
        /// </summary>
        // *** Start programmer edit section *** (ОтчОПрод.Подраз CustomAttributes)

        // *** End programmer edit section *** (ОтчОПрод.Подраз CustomAttributes)
        [PropertyStorage(new string[] {
                "Подраз"})]
        [NotNull()]
        public virtual IIS.Avtomatizaciya_prodazhi3.Подраз Подраз
        {
            get
            {
                // *** Start programmer edit section *** (ОтчОПрод.Подраз Get start)

                // *** End programmer edit section *** (ОтчОПрод.Подраз Get start)
                IIS.Avtomatizaciya_prodazhi3.Подраз result = this.fПодраз;
                // *** Start programmer edit section *** (ОтчОПрод.Подраз Get end)

                // *** End programmer edit section *** (ОтчОПрод.Подраз Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчОПрод.Подраз Set start)

                // *** End programmer edit section *** (ОтчОПрод.Подраз Set start)
                this.fПодраз = value;
                // *** Start programmer edit section *** (ОтчОПрод.Подраз Set end)

                // *** End programmer edit section *** (ОтчОПрод.Подраз Set end)
            }
        }
        
        /// <summary>
        /// Отч о прод.
        /// </summary>
        // *** Start programmer edit section *** (ОтчОПрод.Склады CustomAttributes)

        // *** End programmer edit section *** (ОтчОПрод.Склады CustomAttributes)
        [PropertyStorage(new string[] {
                "Склады"})]
        [NotNull()]
        public virtual IIS.Avtomatizaciya_prodazhi3.Склады Склады
        {
            get
            {
                // *** Start programmer edit section *** (ОтчОПрод.Склады Get start)

                // *** End programmer edit section *** (ОтчОПрод.Склады Get start)
                IIS.Avtomatizaciya_prodazhi3.Склады result = this.fСклады;
                // *** Start programmer edit section *** (ОтчОПрод.Склады Get end)

                // *** End programmer edit section *** (ОтчОПрод.Склады Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчОПрод.Склады Set start)

                // *** End programmer edit section *** (ОтчОПрод.Склады Set start)
                this.fСклады = value;
                // *** Start programmer edit section *** (ОтчОПрод.Склады Set end)

                // *** End programmer edit section *** (ОтчОПрод.Склады Set end)
            }
        }
        
        /// <summary>
        /// Отч о прод.
        /// </summary>
        // *** Start programmer edit section *** (ОтчОПрод.ТЧТовИУс CustomAttributes)

        // *** End programmer edit section *** (ОтчОПрод.ТЧТовИУс CustomAttributes)
        public virtual IIS.Avtomatizaciya_prodazhi3.DetailArrayOfТЧТовИУс ТЧТовИУс
        {
            get
            {
                // *** Start programmer edit section *** (ОтчОПрод.ТЧТовИУс Get start)

                // *** End programmer edit section *** (ОтчОПрод.ТЧТовИУс Get start)
                if ((this.fТЧТовИУс == null))
                {
                    this.fТЧТовИУс = new IIS.Avtomatizaciya_prodazhi3.DetailArrayOfТЧТовИУс(this);
                }
                IIS.Avtomatizaciya_prodazhi3.DetailArrayOfТЧТовИУс result = this.fТЧТовИУс;
                // *** Start programmer edit section *** (ОтчОПрод.ТЧТовИУс Get end)

                // *** End programmer edit section *** (ОтчОПрод.ТЧТовИУс Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчОПрод.ТЧТовИУс Set start)

                // *** End programmer edit section *** (ОтчОПрод.ТЧТовИУс Set start)
                this.fТЧТовИУс = value;
                // *** Start programmer edit section *** (ОтчОПрод.ТЧТовИУс Set end)

                // *** End programmer edit section *** (ОтчОПрод.ТЧТовИУс Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтчОПродE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчОПродE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчОПродE", typeof(IIS.Avtomatizaciya_prodazhi3.ОтчОПрод));
                }
            }
            
            /// <summary>
            /// "ОтчОПродL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчОПродL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчОПродL", typeof(IIS.Avtomatizaciya_prodazhi3.ОтчОПрод));
                }
            }
        }
    }
}
