//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Avtomatizaciya_prodazhi3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отч ост н скл.
    /// </summary>
    // *** Start programmer edit section *** (ОтчОстНСкл CustomAttributes)

    // *** End programmer edit section *** (ОтчОстНСкл CustomAttributes)
    [AutoAltered()]
    [Caption("Отчет остатки на складе")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтчОстНСклE", new string[] {
            "Дата as \'Дата\'",
            "Склады as \'Склад\'",
            "Склады.Склад as \'Склад\'",
            "Номенк as \'Номенклатура\'",
            "Номенк.Номен as \'Номенклатура\'",
            "Колл as \'Количество\'",
            "КолВРез as \'Количество в резерве\'",
            "КолВРез.Количество as \'Количество\'"}, Hidden=new string[] {
            "Склады.Склад",
            "Номенк.Номен",
            "КолВРез.Количество"})]
    [MasterViewDefineAttribute("ОтчОстНСклE", "Склады", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Склад")]
    [MasterViewDefineAttribute("ОтчОстНСклE", "Номенк", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номен")]
    [MasterViewDefineAttribute("ОтчОстНСклE", "КолВРез", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Количество")]
    [View("ОтчОстНСклL", new string[] {
            "Дата as \'Дата\'",
            "Колл as \'Колл\'",
            "Склады.Склад as \'Склад\'",
            "КолВРез.Количество as \'Количество\'",
            "Номенк.Номен as \'Номен\'"})]
    public class ОтчОстНСкл : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private int fКолл;
        
        private IIS.Avtomatizaciya_prodazhi3.Номенк fНоменк;
        
        private IIS.Avtomatizaciya_prodazhi3.КолВРез fКолВРез;
        
        private IIS.Avtomatizaciya_prodazhi3.Склады fСклады;
        
        // *** Start programmer edit section *** (ОтчОстНСкл CustomMembers)

        // *** End programmer edit section *** (ОтчОстНСкл CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ОтчОстНСкл.Дата CustomAttributes)

        // *** End programmer edit section *** (ОтчОстНСкл.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ОтчОстНСкл.Дата Get start)

                // *** End programmer edit section *** (ОтчОстНСкл.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ОтчОстНСкл.Дата Get end)

                // *** End programmer edit section *** (ОтчОстНСкл.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчОстНСкл.Дата Set start)

                // *** End programmer edit section *** (ОтчОстНСкл.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ОтчОстНСкл.Дата Set end)

                // *** End programmer edit section *** (ОтчОстНСкл.Дата Set end)
            }
        }
        
        /// <summary>
        /// Колл.
        /// </summary>
        // *** Start programmer edit section *** (ОтчОстНСкл.Колл CustomAttributes)

        // *** End programmer edit section *** (ОтчОстНСкл.Колл CustomAttributes)
        public virtual int Колл
        {
            get
            {
                // *** Start programmer edit section *** (ОтчОстНСкл.Колл Get start)

                // *** End programmer edit section *** (ОтчОстНСкл.Колл Get start)
                int result = this.fКолл;
                // *** Start programmer edit section *** (ОтчОстНСкл.Колл Get end)

                // *** End programmer edit section *** (ОтчОстНСкл.Колл Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчОстНСкл.Колл Set start)

                // *** End programmer edit section *** (ОтчОстНСкл.Колл Set start)
                this.fКолл = value;
                // *** Start programmer edit section *** (ОтчОстНСкл.Колл Set end)

                // *** End programmer edit section *** (ОтчОстНСкл.Колл Set end)
            }
        }
        
        /// <summary>
        /// Отч ост н скл.
        /// </summary>
        // *** Start programmer edit section *** (ОтчОстНСкл.КолВРез CustomAttributes)

        // *** End programmer edit section *** (ОтчОстНСкл.КолВРез CustomAttributes)
        [PropertyStorage(new string[] {
                "КолВРез"})]
        [NotNull()]
        public virtual IIS.Avtomatizaciya_prodazhi3.КолВРез КолВРез
        {
            get
            {
                // *** Start programmer edit section *** (ОтчОстНСкл.КолВРез Get start)

                // *** End programmer edit section *** (ОтчОстНСкл.КолВРез Get start)
                IIS.Avtomatizaciya_prodazhi3.КолВРез result = this.fКолВРез;
                // *** Start programmer edit section *** (ОтчОстНСкл.КолВРез Get end)

                // *** End programmer edit section *** (ОтчОстНСкл.КолВРез Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчОстНСкл.КолВРез Set start)

                // *** End programmer edit section *** (ОтчОстНСкл.КолВРез Set start)
                this.fКолВРез = value;
                // *** Start programmer edit section *** (ОтчОстНСкл.КолВРез Set end)

                // *** End programmer edit section *** (ОтчОстНСкл.КолВРез Set end)
            }
        }
        
        /// <summary>
        /// Отч ост н скл.
        /// </summary>
        // *** Start programmer edit section *** (ОтчОстНСкл.Номенк CustomAttributes)

        // *** End programmer edit section *** (ОтчОстНСкл.Номенк CustomAttributes)
        [PropertyStorage(new string[] {
                "Номенк"})]
        [NotNull()]
        public virtual IIS.Avtomatizaciya_prodazhi3.Номенк Номенк
        {
            get
            {
                // *** Start programmer edit section *** (ОтчОстНСкл.Номенк Get start)

                // *** End programmer edit section *** (ОтчОстНСкл.Номенк Get start)
                IIS.Avtomatizaciya_prodazhi3.Номенк result = this.fНоменк;
                // *** Start programmer edit section *** (ОтчОстНСкл.Номенк Get end)

                // *** End programmer edit section *** (ОтчОстНСкл.Номенк Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчОстНСкл.Номенк Set start)

                // *** End programmer edit section *** (ОтчОстНСкл.Номенк Set start)
                this.fНоменк = value;
                // *** Start programmer edit section *** (ОтчОстНСкл.Номенк Set end)

                // *** End programmer edit section *** (ОтчОстНСкл.Номенк Set end)
            }
        }
        
        /// <summary>
        /// Отч ост н скл.
        /// </summary>
        // *** Start programmer edit section *** (ОтчОстНСкл.Склады CustomAttributes)

        // *** End programmer edit section *** (ОтчОстНСкл.Склады CustomAttributes)
        [PropertyStorage(new string[] {
                "Склады"})]
        [NotNull()]
        public virtual IIS.Avtomatizaciya_prodazhi3.Склады Склады
        {
            get
            {
                // *** Start programmer edit section *** (ОтчОстНСкл.Склады Get start)

                // *** End programmer edit section *** (ОтчОстНСкл.Склады Get start)
                IIS.Avtomatizaciya_prodazhi3.Склады result = this.fСклады;
                // *** Start programmer edit section *** (ОтчОстНСкл.Склады Get end)

                // *** End programmer edit section *** (ОтчОстНСкл.Склады Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчОстНСкл.Склады Set start)

                // *** End programmer edit section *** (ОтчОстНСкл.Склады Set start)
                this.fСклады = value;
                // *** Start programmer edit section *** (ОтчОстНСкл.Склады Set end)

                // *** End programmer edit section *** (ОтчОстНСкл.Склады Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтчОстНСклE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчОстНСклE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчОстНСклE", typeof(IIS.Avtomatizaciya_prodazhi3.ОтчОстНСкл));
                }
            }
            
            /// <summary>
            /// "ОтчОстНСклL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчОстНСклL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчОстНСклL", typeof(IIS.Avtomatizaciya_prodazhi3.ОтчОстНСкл));
                }
            }
        }
    }
}
