//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Avtomatizaciya_prodazhi3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотруд.
    /// </summary>
    // *** Start programmer edit section *** (Сотруд CustomAttributes)

    // *** End programmer edit section *** (Сотруд CustomAttributes)
    [AutoAltered()]
    [Caption("Сотрудники")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СотрудE", new string[] {
            "ФИО as \'ФИО\'",
            "Долж as \'Должность\'",
            "Долж.Должность as \'Должность\'"}, Hidden=new string[] {
            "Долж.Должность"})]
    [MasterViewDefineAttribute("СотрудE", "Долж", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Должность")]
    [View("СотрудL", new string[] {
            "ФИО as \'ФИО\'",
            "Долж.Должность as \'Должность\'"})]
    public class Сотруд : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private IIS.Avtomatizaciya_prodazhi3.Долж fДолж;
        
        // *** Start programmer edit section *** (Сотруд CustomMembers)

        // *** End programmer edit section *** (Сотруд CustomMembers)

        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Сотруд.ФИО CustomAttributes)

        // *** End programmer edit section *** (Сотруд.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Сотруд.ФИО Get start)

                // *** End programmer edit section *** (Сотруд.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Сотруд.ФИО Get end)

                // *** End programmer edit section *** (Сотруд.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотруд.ФИО Set start)

                // *** End programmer edit section *** (Сотруд.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Сотруд.ФИО Set end)

                // *** End programmer edit section *** (Сотруд.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Сотруд.
        /// </summary>
        // *** Start programmer edit section *** (Сотруд.Долж CustomAttributes)

        // *** End programmer edit section *** (Сотруд.Долж CustomAttributes)
        [PropertyStorage(new string[] {
                "Долж"})]
        [NotNull()]
        public virtual IIS.Avtomatizaciya_prodazhi3.Долж Долж
        {
            get
            {
                // *** Start programmer edit section *** (Сотруд.Долж Get start)

                // *** End programmer edit section *** (Сотруд.Долж Get start)
                IIS.Avtomatizaciya_prodazhi3.Долж result = this.fДолж;
                // *** Start programmer edit section *** (Сотруд.Долж Get end)

                // *** End programmer edit section *** (Сотруд.Долж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотруд.Долж Set start)

                // *** End programmer edit section *** (Сотруд.Долж Set start)
                this.fДолж = value;
                // *** Start programmer edit section *** (Сотруд.Долж Set end)

                // *** End programmer edit section *** (Сотруд.Долж Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СотрудE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудE", typeof(IIS.Avtomatizaciya_prodazhi3.Сотруд));
                }
            }
            
            /// <summary>
            /// "СотрудL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудL", typeof(IIS.Avtomatizaciya_prodazhi3.Сотруд));
                }
            }
        }
    }
}
