//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Avtomatizaciya_prodazhi3
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состояние отгрузки.
    /// </summary>
    // *** Start programmer edit section *** (СостОтгр CustomAttributes)

    // *** End programmer edit section *** (СостОтгр CustomAttributes)
    public enum СостОтгр
    {
        
        // *** Start programmer edit section *** (СостОтгр.Отгруж CustomAttributes)

        // *** End programmer edit section *** (СостОтгр.Отгруж CustomAttributes)
        Отгруж,
        
        // *** Start programmer edit section *** (СостОтгр.НеОтгруж CustomAttributes)

        // *** End programmer edit section *** (СостОтгр.НеОтгруж CustomAttributes)
        НеОтгруж,
        
        // *** Start programmer edit section *** (СостОтгр.ЧастичОтгруз CustomAttributes)

        // *** End programmer edit section *** (СостОтгр.ЧастичОтгруз CustomAttributes)
        ЧастичОтгруз,
    }
}
