//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Avtomatizaciya_prodazhi3
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состояние оплаты.
    /// </summary>
    // *** Start programmer edit section *** (СостОпл CustomAttributes)

    // *** End programmer edit section *** (СостОпл CustomAttributes)
    public enum СостОпл
    {
        
        // *** Start programmer edit section *** (СостОпл.ЧастичноОплачен CustomAttributes)

        // *** End programmer edit section *** (СостОпл.ЧастичноОплачен CustomAttributes)
        ЧастичноОплачен,
        
        // *** Start programmer edit section *** (СостОпл.НеОплачен CustomAttributes)

        // *** End programmer edit section *** (СостОпл.НеОплачен CustomAttributes)
        НеОплачен,
        
        // *** Start programmer edit section *** (СостОпл.Оплачен CustomAttributes)

        // *** End programmer edit section *** (СостОпл.Оплачен CustomAttributes)
        Оплачен,
    }
}
